In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/sentiment140/training.1600000.processed.noemoticon.csv

In [2]:
import pandas as pd 
import numpy as np
import re

In [3]:
df =pd.read_csv("/kaggle/input/sentiment140/training.1600000.processed.noemoticon.csv",encoding='ISO-8859-1')

In [4]:
df

,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer. You shoulda got David Carr of Third Day to do it. ;D"
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew
...,...,...,...,...,...,...
1599994,4,2193601966,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,AmandaMarie1028,Just woke up. Having no school is the best fee...
1599995,4,2193601969,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,TheWDBoards,TheWDB.com - Very cool to hear old Walt interv...
1599996,4,2193601991,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,bpbabe,Are you ready for your MoJo Makeover? Ask me f...
1599997,4,2193602064,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,tinydiamondz,Happy 38th Birthday to my boo of alll time!!! ...
1599998,4,2193602129,Tue Jun 16 08:40:50 PDT 2009,NO_QUERY,RyanTrevMorris,happy #charitytuesday @theNSPCC @SparksCharity...

In [5]:
columnames =['target','id','date','flag','user','text']

In [6]:
df = pd.read_csv("/kaggle/input/sentiment140/training.1600000.processed.noemoticon.csv",names=columnames,encoding='ISO-8859-1')

In [7]:
df.head(100)

,target,id,date,flag,user,text
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
...,...,...,...,...,...,...
95,0,1467836448,Mon Apr 06 22:26:27 PDT 2009,NO_QUERY,Dogbook,Strider is a sick little puppy http://apps.fa...
96,0,1467836500,Mon Apr 06 22:26:28 PDT 2009,NO_QUERY,natalieantipas,"so rylee,grace...wana go steve's party or not?..."
97,0,1467836576,Mon Apr 06 22:26:29 PDT 2009,NO_QUERY,timdonnelly,"hey, I actually won one of my bracket pools! T..."
98,0,1467836583,Mon Apr 06 22:26:29 PDT 2009,NO_QUERY,homeworld,"@stark YOU don't follow me, either and i work..."
99,0,1467836859,Mon Apr 06 22:26:33 PDT 2009,NO_QUERY,willy_chaz,A bad nite for the favorite teams: Astros and ...

In [8]:
df=df.drop(["id","date","flag","user"],axis = 1)

In [9]:
df.head(10)

   target                                               text
0       0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1       0  is upset that he can't update his Facebook by ...
2       0  @Kenichan I dived many times for the ball. Man...
3       0    my whole body feels itchy and like its on fire
4       0  @nationwideclass no, it's not behaving at all....
5       0                      @Kwesidei not the whole crew
6       0                                        Need a hug
7       0  @LOLTrish hey  long time no see! Yes.. Rains a...
8       0               @Tatiana_K nope they didn't have it
9       0                          @twittera que me muera ?

In [10]:
df.target.unique()

array([0, 4])

In [11]:
df.isnull().sum()

target    0
text      0
dtype: int64

In [12]:
df.head(10)

   target                                               text
0       0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1       0  is upset that he can't update his Facebook by ...
2       0  @Kenichan I dived many times for the ball. Man...
3       0    my whole body feels itchy and like its on fire
4       0  @nationwideclass no, it's not behaving at all....
5       0                      @Kwesidei not the whole crew
6       0                                        Need a hug
7       0  @LOLTrish hey  long time no see! Yes.. Rains a...
8       0               @Tatiana_K nope they didn't have it
9       0                          @twittera que me muera ?

In [13]:
df.target.unique()

array([0, 4])

In [14]:
df.target.unique()

array([0, 4])

In [15]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [16]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [17]:
port_stem =PorterStemmer()

In [18]:
def stemming(content):
    stemmed_content = re.sub('[^a-zA-Z]', ' ', content)
    stemmed_content = stemmed_content.lower()
    stemmed_content = stemmed_content.split()
    stemmed_content = [port_stem.stem(word) for word in stemmed_content if word not in stopwords.words('english')]
    stemmed_content = ' '.join(stemmed_content)
    return stemmed_content

In [19]:
df["text"] = df["text"].apply(stemming)

In [21]:
df.head(10)

   target                                               text
0       0  switchfoot http twitpic com zl awww bummer sho...
1       0  upset updat facebook text might cri result sch...
2       0  kenichan dive mani time ball manag save rest g...
3       0                    whole bodi feel itchi like fire
4       0                      nationwideclass behav mad see
5       0                                kwesidei whole crew
6       0                                           need hug
7       0  loltrish hey long time see ye rain bit bit lol...
8       0                                     tatiana k nope
9       0                                 twittera que muera

In [26]:
x=df["text"].values

In [27]:
y = df['target'].values

In [28]:
x

array(['switchfoot http twitpic com zl awww bummer shoulda got david carr third day',
       'upset updat facebook text might cri result school today also blah',
       'kenichan dive mani time ball manag save rest go bound', ...,
       'readi mojo makeov ask detail',
       'happi th birthday boo alll time tupac amaru shakur',
       'happi charitytuesday thenspcc sparkschar speakinguph h'],
      dtype=object)

In [30]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,stratify = y, random_state = 2020)

In [32]:
x_train.size

1280000

In [33]:
from sklearn.pipeline import Pipeline

In [36]:
from sklearn.naive_bayes import MultinomialNB

In [37]:
clf = Pipeline([
    ("vectorizer",TfidfVectorizer()),
    ("multi Nb",MultinomialNB())
])

In [38]:
clf.fit(x_train,y_train)

Pipeline(steps=[('vectorizer', TfidfVectorizer()),
                ('multi Nb', MultinomialNB())])

In [39]:
y_pre = clf.predict(x_test)

In [40]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pre))

              precision    recall  f1-score   support

           0       0.74      0.78      0.76    160000
           4       0.77      0.73      0.75    160000

    accuracy                           0.76    320000
   macro avg       0.76      0.76      0.76    320000
weighted avg       0.76      0.76      0.76    320000

In [41]:
accuracy = accuracy_score(y_test, y_pre)
print("Accuracy:", accuracy)

Accuracy: 0.75556875

In [71]:
with open("pipeline_model.pkl", "wb") as f:
    pickle.dump(clf, f)

In [53]:
clf2 = Pipeline([
    ("vectorizer",TfidfVectorizer()),
    ("logistic",LogisticRegression(max_iter=2000))
])

In [54]:
clf2.fit(x_train,y_train)

Pipeline(steps=[('vectorizer', TfidfVectorizer()),
                ('logistic', LogisticRegression(max_iter=2000))])

In [74]:
y_pre = clf2.predict(x_test)

In [75]:
accuracy = accuracy_score(y_test, y_pre)
print("Accuracy:", accuracy)

Accuracy: 0.7776

In [77]:
 import os
import zipfile

# 1) save pickle
import pickle
with open("model.pkl", "wb") as f:
    pickle.dump(clf2, f)

# 2) zip it (optional, if you have many files)
zip_name = "my_pickles.zip"
with zipfile.ZipFile(zip_name, "w", zipfile.ZIP_DEFLATED) as z:
    z.write("model.pkl")

# 3) show link (Jupyter) – works in many Kaggle environments
from IPython.display import FileLink
FileLink(zip_name)

/kaggle/working/my_pickles.zip

In [80]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
import pickle

# Create pipeline
pipeline = Pipeline([
    ("vectorizer", TfidfVectorizer()),
    ("clf", MultinomialNB())
])

# Fit the pipeline
pipeline.fit(x_train, y_train)

# Save AFTER fitting
with open("pipeline_model2.pkl", "wb") as f:
    pickle.dump(pipeline, f)

print("Pipeline saved successfully!")

Pipeline saved successfully!

In [79]:
with open("pipeline_model.pkl", "rb") as f:
    pipeline = pickle.load(f)

pipeline.predict(["this is good"])

array([4])